# permissions for end users to view rules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rules-controller
    app.kubernetes.io/managed-by: kustomize
  name: rules-viewer-role
rules:
- apiGroups:
  - byron.fun
  resources:
  - rules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - byron.fun
  resources:
  - rules/status
  verbs:
  - get
